on: push
name: deploy
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./gestion_viajes
          file: ./gestion_viajes/Dockerfile
          push: true
          tags: ${{ github.repository }}:${{ github.sha }}
